---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kumar-github/microservices-configuration.git
          search-paths: config
  application:
    name: spring-cloud-config-server
    
server:
  port: 8888